version: '3.9'

networks:
  backend:


services:
  customerdb:
     container_name: customer-db
     image: mcr.microsoft.com/mssql/server:2019-latest
     environment:
       - SA_PASSWORD=NewStrongPassword123!
       - ACCEPT_EULA=Y
     ports:
       - "1433:1433" 
     networks:
       - backend
  customerwebapi:
    container_name: customerwebapi
    image: ${DOCKER_REGISTRY-}customerwebapi
    build:
      context: .
      dockerfile: CustomerWebApi/Dockerfile
    networks:
      - backend
    environment:
      - ConnectionStrings__DefaultConnection=Server=customer;Database=microarchitecture_db;User Id=sa;Password=NewStrongPassword123!;TrustServerCertificate=true;


  productwebapi:
    image: ${DOCKER_REGISTRY-}productwebapi
    build:
      context: .
      dockerfile: ProductWebApi/Dockerfile


  orderwebapi:
    image: ${DOCKER_REGISTRY-}orderwebapi
    build:
      context: .
      dockerfile: OrderWebApi/Dockerfile

